docs/content/terraform/_index.md
docs/content/terraform/gettingStarted.md
docs/hugo.toml
docs/themes/hugo-geekdoc/layouts/partials/site-header.html

- branding
- remove banner
- recommend accelerator more forcefully

feat: minor terraform tweaks

---

docs/data/consent.yaml
docs/layouts/_default/baseof.html
docs/layouts/partials/consent.html
docs/layouts/partials/site-footer.html
docs/static/js/clarity.js

Add Microsoft Clarity Integration

feat: add Microsoft Clarity integration and update site layout

---

docs/content/accelerator/startermodules/terraform-platform-landing-zone/_index.md
docs/content/accelerator/userguide/0_planning.md
docs/content/accelerator/userguide/1_prerequisites/platform-subscriptions.md
docs/content/accelerator/userguide/1_prerequisites/service-principal.md
docs/content/accelerator/userguide/2_start/bicep-azuredevops.md
docs/content/accelerator/userguide/2_start/bicep-github.md
docs/content/accelerator/userguide/2_start/bicep-local.md
docs/content/accelerator/userguide/2_start/terraform-azuredevops.md
docs/content/accelerator/userguide/2_start/terraform-github.md
docs/content/accelerator/userguide/2_start/terraform-local.md

Various doc fixes in preparation for release

fix: tidy docs ready for release

---

docs/content/accelerator/startermodules/terraform-platform-landing-zone/configuration.md
docs/content/accelerator/troubleshooting.md

Update the advanced docs to include new module versions

docs: update module versions

---

docs/content/accelerator/troubleshooting.md

fix: troubleshooting item title

---

docs/content/accelerator/userguide/1_prerequisites/platform-subscriptions.md

Update the docs to add clarity around platform subscription initial location.

docs: subscription placement

---

docs/content/accelerator/userguide/2_start/bicep-azuredevops.md
docs/content/accelerator/userguide/2_start/bicep-github.md
docs/content/accelerator/userguide/2_start/bicep-local.md
docs/content/accelerator/userguide/2_start/terraform-azuredevops.md
docs/content/accelerator/userguide/2_start/terraform-github.md
docs/content/accelerator/userguide/2_start/terraform-local.md

Add a step to make sure latest module version is being run in case there was a release after starting.

docs: add update module step

---

docs/content/accelerator/startermodules/terraform-platform-landing-zone/scenarios/multi-region-hub-and-spoke-vnet-with-nva.md

Fix a link in the docs for multi region NVA

docs: fix multi region nva tfvars link

---

DEVELOPER.md
docs/content/accelerator/faq.md
docs/content/accelerator/userguide/1_prerequisites/_index.md

Update pre-reqs, FAQs and developer docs

chore: improve docs

---

docs/content/accelerator/faq.md

There is a typo: overrwrite line 97

Fix Typo in faq.md

---

docs/content/accelerator/userguide/0_planning.md
docs/content/accelerator/userguide/1_prerequisites/azuredevops.md
docs/content/accelerator/userguide/3_deploy.md

Fixing 3 typos in the doc

---

docs/content/accelerator/startermodules/terraform-platform-landing-zone/options/policy-assignment.md

docs: correct sandbox naming in policy-assignment.md

---

docs/content/accelerator/startermodules/terraform-platform-landing-zone/options/policy-assignment.md

Update the docs, so they correctly include the override archetype.

fix: override policy assignments option

---

.gitmodules

Adds dark for now whilst we test

feat: add arch editor as static content

---

docs/content/accelerator/startermodules/terraform-platform-landing-zone/scenarios/_index.md
docs/content/accelerator/startermodules/terraform-platform-landing-zone/scenarios/single-region-hub-and-spoke-vnet-with-nva.md
docs/content/accelerator/startermodules/terraform-platform-landing-zone/scenarios/single-region-virtual-wan-with-nva.md

Adding single region NVA scenario based on internal and external feedback.
https://github.com/Azure/ALZ-PowerShell-Module/issues/326

feat: add single region nva scenario

---

docs/content/accelerator/faq.md
docs/content/accelerator/userguide/3_deploy.md

Added a note to inform users on clean up information available on FAQs
Closes: https://github.com/Azure/ALZ-PowerShell-Module/issues/242

docs: add note on bootstrap clean up in run phase

---

docs/content/accelerator/startermodules/terraform-platform-landing-zone/options/policy-assignment.md

Indent plus code block means that syntax highlighting was broken

fix: indent + prefomatted issue

---

docs/content/accelerator/startermodules/terraform-platform-landing-zone/options/bastion.md
docs/content/accelerator/startermodules/terraform-platform-landing-zone/options/ddos.md
docs/content/accelerator/startermodules/terraform-platform-landing-zone/options/dns.md
docs/content/accelerator/startermodules/terraform-platform-landing-zone/options/gateways.md

Updated the relevant options to match the config files that will be deployed in the latest version.

docs: update option instructions to align with simplified config in latest release

---

docs/content/accelerator/startermodules/terraform-platform-landing-zone/options/ddos.md

Update option to include second DDOS assignment: https://github.com/Azure/ALZ-PowerShell-Module/issues/356

fix: add missing ddos policy override

---

docs/content/terraform/migration/managementgroups.md
docs/content/terraform/migration/migration-faq.md
docs/content/terraform/migration/resources.md
docs/static/examples/tf/migration/lib/archetype_definitions/root.alz_archetype_override.json
docs/static/examples/tf/migration/lib/architecture_definitions/alz.alz_architecture_definition.json
docs/static/examples/tf/migration/lib/role_definitions/application_owners.alz_role_definition.json
docs/static/examples/tf/migration/lib/role_definitions/network_management.alz_role_definition.json
docs/static/examples/tf/migration/lib/role_definitions/network_subnet_contributor.alz_role_definition.json
docs/static/examples/tf/migration/lib/role_definitions/security_operations.alz_role_definition.json
docs/static/examples/tf/migration/lib/role_definitions/subscription_owner.alz_role_definition.json
docs/static/examples/tf/migration/platform-landing-zone.hub-and-spoke.auto.tfvars
docs/static/examples/tf/migration/platform-landing-zone.virtual-wan.auto.tfvars

Add the management group migration docs.

docs: migration management groups

---

docs/content/accelerator/startermodules/terraform-platform-landing-zone/options/ama.md

Remove redundant section from AMA docs.
Fixes: https://github.com/Azure/ALZ-PowerShell-Module/issues/380

fix: ama docs

---

docs/content/accelerator/startermodules/terraform-platform-landing-zone/options/amba.md

Documentation to get users up and running with Azure Monitor Baseline Alerts.
This should initially be enough to get users up and running with minimum input. I've also provided all potential inputs for the policy default values to support a more complex deployment scenario.

feat: Azure Monitor Baseline Alert Documentation
